---
- name: Breakfix Grading 2
  become: true
  become_user: root
  hosts: nodea 
  tasks:

     - name: Pull the grading script
       get_url:
          url: "http://people.redhat.com/rrajaram/.clusterha/break/break2-grading.sh"
          dest: /usr/local/bin/
          mode: '0755'
       no_log: true


     - name: Execute the grading script
       shell: /usr/local/bin/break2-grading.sh
       register: result2
       no_log: true

     - name: Break  2 challenge code
       debug:
          var: result2

