---
- name: Setting Break 5 environment
  become: true
  become_user: root
  hosts: cluster
  tasks:

     - name: Reset LV
       shell: umount /var/lib/mysql; lvremove /dev/mariadb/mariadb_lv -y --config 'global {locking_type = 0}'; vgremove mariadb -y --config 'global {locking_type = 0}'; pvremove /dev/sdb --config 'global {locking_type = 0}'    
       ignore_errors: yes
       when: ansible_hostname == "nodea"

     - name: Setup VG
       shell: pvcreate /dev/sdb -y -ff --config 'global {locking_type = 0}'
       when: ansible_hostname == "nodea"

     - name: Setup VG
       shell: vgcreate mariadb /dev/sdb -f --config 'global {locking_type = 0}'
       when: ansible_hostname == "nodea"

     - name: Lvcreate
       shell: lvcreate -l 100%FREE -n mariadb_lv mariadb  -y --config 'global {locking_type = 0}'
       when: ansible_hostname == "nodea"
     

     - name: Create FS
       shell:  mkfs.xfs /dev/mariadb/mariadb_lv 
       when: ansible_hostname == "nodea"

     - name:  Mount the volume 
       shell: mount /dev/mariadb/mariadb_lv /var/lib/mysql; chown mysql.mysql /var/lib/mysql
       when: ansible_hostname == "nodea"

     - name: Unarchive a file that is already on the remote machine
       unarchive:
        src: 
        dest: /var/lib/mysql
        owner: mysql
        remote_src: yes
       when: ansible_hostname == "nodea"     

     - name: Restoring permissions
       shell: mkdir -p /var/lib/mysql/log; chown mysql.mysql /var/lib/mysql/log; restorecon -R /var/lib/mysql
       when: ansible_hostname == "nodea"
        
     - name:  Unmount
       shell: umount /var/lib/mysql
       when: ansible_hostname == "nodea"

     - name: locationaction 1
       local_action:
        module: get_url
        url: "https://raw.githubusercontent.com/pntae-training/courses/master/tech-breakfix-ha-001/hacluster/tasks/break/break5-halvm.sh"
        dest: /usr/local/bin/
        mode: '0755'
       become: yes

     - name: destroy node c 
       shell: pcs cluster destroy
       when: ansible_hostname == "nodec"


     - name: enable halvm
       local_action:
         module: shell
         cmd: /usr/local/bin/break5-halvm.sh
       become: false
    
     - name: reboot cluster node
       debug:
        msg: rebooting the nodes

     - name: Reboot node and stop polling.
       shell: reboot
       async: 10 # Do not care for 10 sec
       poll: 0 # Fire & Forget


     - name: wait for host to finish reb00t
       wait_for:
        port: "{{ (ansible_port|default(ansible_ssh_port))|default(22) }}"
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10  # Do not check for at least 10 sec
       connection: local

     - name: localaction 2
       local_action:
         module: shell
         cmd: sleep 15


     - name: Pull the breakfix 5 environment files
       get_url:
          url: "https://raw.githubusercontent.com/pntae-training/courses/master/tech-breakfix-ha-001/hacluster/tasks/break/twonode-mysql-cluster.tar.bz2"
          dest: /var/tmp/
       when: ansible_hostname == "nodea"

     - name: Resetting the cluster for BreakFix 5
       shell: pcs cluster destroy --all
       ignore_errors: yes
       when: ansible_hostname == "nodea"

     - name: Restoring cluster
       shell:
         cmd: pcs config restore twonode-mysql-cluster.tar.bz2
         chdir: /var/tmp/
       when: ansible_hostname == "nodea"

     - name: Starting cluster
       shell: pcs cluster enable; pcs cluster start --all; sleep 10; pcs cluster start --all &> /dev/null
       when: ansible_hostname == "nodea"
       ignore_errors: yes

     - name: Restoring cluster
       shell:
         cmd: vgchange -cy mariadb -y
       when: ansible_hostname == "nodea"
 

     - name: Breaking the node Part B BreakFixReset 1
       shell: sleep 15; pcs resource cleanup
       when: ansible_hostname == "nodea"


     - name: Breaking the node Part A BreakFix 2
       get_url:
          url: "https://raw.githubusercontent.com/pntae-training/courses/master/tech-breakfix-ha-001/hacluster/tasks/break/break5-log.sh"
          dest: /usr/local/bin/
          mode: '0755'
       when: ansible_hostname != "nodec"

     - name: Breaking the node Part B BreakFix 2
       shell: /usr/local/bin/break5-log.sh
       when: ansible_hostname != "nodec"








#     - name: Executing local script
#       local_action:
#         module: shell
#         cmd: sleep 60
#       become: false
  

#     - name: Pull backup file
#       get_url:
#          url: "http://10.65.200.3/twonode-cluster-break5"
#          dest: /var/tmp/

#     - name: Resetting the cluster for BreakFix 3
#       shell: pcs cluster destroy --all


#     - name: Restoring cluster
#       shell:
#          cmd: pcs config restore twonode-cluster-break5
#          chdir: /var/tmp/

#     - name: Starting cluster
#       shell:  pcs cluster start --all

#     - name: Executing local script
#       local_action:
#         module: shell
#         cmd: /usr/local/sbin/break1reset-2.sh
#       become: false

