---
- name: PCS cluster reset
  become: true
  become_user: root
  hosts: nodea
  tasks:

     - name: Pull grading script
       get_url:
          url: "https://raw.githubusercontent.com/pntae-training/courses/master/tech-breakfix-ha-001/hacluster/tasks/break/break1-grading.sh"
          dest: /usr/local/bin/
          mode: '0755'
       no_log: true


     - name: Running the grading script
       shell: /usr/local/bin/break1-grading.sh
       register: result1
       no_log: true

     - name: Break  1 challenge result
       debug:
          var: result1


