---
- name: Installation and setup iscsi and nfs server 
  become: true
  become_user: root
  hosts: iscsiserver
  tasks:

     - name: iscsi target server configuration. Get the script
       get_url:
          url: "http://people.redhat.com/rrajaram/.breakfix1/target-iscsi-server.sh"
          dest: /usr/local/bin/
          mode: '0755'

     - name: run the script and setup iscsi server
       shell: /usr/local/bin/target-iscsi-server.sh

